package guru.framework.booklibraryapp.domain;

public enum BookEvent {

	BORROW_REQUEST_APPROVED, BORROW_REQUEST_DECLINED, IN_REPAIR_EVENT, IN_REPAIR_ERROR_EVENT, OUT_OF_STOCK_EVENT,OUT_OF_STOCK_ERROR_EVENT

}
